### ISSUE TITLE
Endianness of format?

### ISSUE THREAD

**Issue by kozross** [prusa3d/libbgcode#25]
The specification describes a binary format, but does not specify its endianness. What is it?

**Comment by cmsj** [comment]
The [spec](https://github.com/prusa3d/libbgcode/blob/main/doc/specifications.md) states that the second 4 bytes of the file are an unsigned 32bit integer containing the version of the format being used, and that this is currently unconditionally `1`.

That's super helpful for figuring out the endianness because there will only be a single bit set to 1 in those four bytes, and it'll either be in the first byte (little endian) or the last byte (big endian).

It's also very helpful that there's a [sample bgcode file](https://github.com/prusa3d/libbgcode/blob/main/tests/data/mini_cube_b.bgcode) in this repo, so we can immediately inspect it and determine the answer.

To do so, we'll use a very nifty command that can give us a nicely outputted binary dump of just the bytes we're interested in:

```
❯ xxd -b -l 4 -seek 4 mini_cube_b.bgcode
00000004: 00000001 00000000 00000000 00000000                    ....
```

So we can see there that the `1` is in the first of the 4 bytes, which tells us this it's little endian 🙂

It's perhaps worth noting though that [the relevant code](https://github.com/prusa3d/libbgcode/blob/e1b6b45d2fdeb7bd527ea08c2a31fb4843c4af2d/src/LibBGCode/core/core.cpp#L6) is just using `fwrite()` so technically will produce files of whatever the host byte order is, which *may* be an issue for anyone trying to run this on more esoteric big-endian machines.

I'm pretty sure the STM32 Prusa uses on the Mini/Mk4/XL, and the ATmega on the Mk3, are little endian, so it probably makes sense to specify that as the preferred order in the bgcode format and avoid having to do byteswapping on those little CPUs. As to whether or not someone wants to patch this library to ensure it's writing little endian even on a big endian machine.... I guess we'll see when the first sparc64 or IBM zOS user appears 😉

**Comment by bubnikv** [comment]
We should document the endianness. We had a discussion internally on this
topic.

The format is little endian only. The library currently likely does not
work on big endian machines, as of now we just plan to detect a big endian
system and refuse to compile. AFAIK I don't expect the library to be ever
executed on a big endian system.

so 21. 10. 2023 v 2:43 odesílatel Chris Jones ***@***.***>
napsal:

**Comment by tamasmeszaros** [comment]
The endianness is now mentioned in the specification (as of 1ebf68cc7d93a3e7824e2b5c5e4d6e2bbbfd3c28)
The library should work now on both types of systems, although it was not tested on BE architectures. The format itself will always be LE.
